<script lang="ts">
  import { navigate } from "svelte-routing";
  import { isSetupStore, siteStore } from "../stores";
  import { Card, Screen, error, success, MarkdownEditor } from "../structure/index";

  let shortName = "";
  let name = "";
  let description = "";
  let domain = "";
  let code = "";
  let title = "";
  let firstName = "";
  let lastName = "";
  let email = "";
  let emailConfirm = "";
  let password = "";
  let passwordConfirm = "";
  let siteTechnicalContact = ""

  const save = async () => {
    // do some basic checks first
    if(email !== emailConfirm){
      return error("Emails Do Not Match", `You entered ${email} and ${emailConfirm}. These must match.`)
    }
    if(password !== passwordConfirm){
      return error("Passwords Do Not Match", `Please re-enter your password and password confirmation.`)
    }
    const data = {
      code,
      site: {
        name,
        shortName,
        description,
        domain,
        siteTechnicalContact,
      },
      user: {
        title,
        firstName,
        lastName,
        email,
        password
      }
    }

    // check for missing data
    const missingFields: string[] = [];
    if(data.code === ""){
      missingFields.push("Site Code");
    }
    if(data.site.name === ""){
      missingFields.push("Site Name");
    }
    if(data.site.shortName === ""){
      missingFields.push("Site Short Name");
    }
    if(data.site.description === ""){
      missingFields.push("Site Description");
    }
    if(data.site.domain === ""){
      missingFields.push("Domain");
    }
    if(data.site.siteTechnicalContact === ""){
      missingFields.push("Technical Contact");
    }
    if(data.user.firstName === ""){
      missingFields.push("User First name");
    }
    if(data.user.lastName === ""){
      missingFields.push("User Last name");
    }
    if(data.user.email === ""){
      missingFields.push("User Email");
    }
    if(data.user.password === ""){
      missingFields.push("User Password");
    }

    if(missingFields.length > 0){
      return error("Missing Fields", `You are missing values for the following fields: <ul><li>${missingFields.join('</li><li>')}</li>`, {
        duration: missingFields.length * 2000
      })
    }

    // now try to save
  }
</script>

<Screen ignoreAuth>
  <div class="row">
    <div class="col-12">
      <Card>
        <p class="text-title">Welcome !</p>
      </Card>
    </div>
  </div>

  <div class="row">
    <div class="col-8">
      <Card title="Site Configuration">
        <div class="row">
          <div class="col-4">
            <label for="code">Site Code</label>
            <input type="text" id="code" bind:value={code} class="form-control" />
            <span class="form-control-description">The code generated by the API server for verification.</span>
          </div>
          <div class="col-4">
            <label for="name">Site Name</label>
            <input type="text" id="name" bind:value={name} class="form-control" />
            <span class="form-control-description">The name of the site or organization.</span>
          </div>
          <div class="col-4">
            <label for="shortName">Short Name</label>
            <input type="text" id="shortName" bind:value={shortName} class="form-control" />
            <span class="form-control-description">A short name for the organization, without spaces. Used for organizing assets.</span>
          </div>
        </div>

        <div class="row">
          <div class="col-4">
            <label for="domain">Domain</label>
            <input type="text" id="domain" bind:value={domain} class="form-control" />
            <span class="form-control-description">The domain for this site.</span>
          </div>
          <div class="col-4">
            <label for="siteTechnicalContact">Technical Contact</label>
            <input type="text" id="siteTechnicalContact" bind:value={siteTechnicalContact} class="form-control" />
            <span class="form-control-description">The email address or contact information for users who need technical support.</span>
          </div>
        </div>

        <div class="row">
          <div class="col-12">
            <label for="code">Description</label>
            <span class="form-control-description">The site's description, in Markdown. This will be displayed on the homepage of the site.</span>
            <MarkdownEditor bind:value={description} />
          </div>
        </div>
      </Card>
    </div>

    <div class="col-4">
      <Card title="Administrator Information">
        <div class="row">
          <div class="col-12">
            <label for="title">Title</label>
            <input type="text" id="title" bind:value={title} class="form-control" />
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <label for="firstName">First Name</label>
            <input type="text" id="firstName" bind:value={firstName} class="form-control" />
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <label for="lastName">Last Name</label>
            <input type="text" id="lastName" bind:value={lastName} class="form-control" />
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <label for="email">Email</label>
            <input type="email" id="email" bind:value={email} class="form-control" />
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <label for="emailConfirm">Email Confirm</label>
            <input type="email" id="emailConfirm" bind:value={emailConfirm} class="form-control" />
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <label for="password">Password</label>
            <input type="password" id="password" bind:value={password} class="form-control" />
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <label for="passwordConfirm">Confirm Password</label>
            <input type="password" id="passwordConfirm" bind:value={passwordConfirm} class="form-control" />
          </div>
        </div>
      </Card>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <button class="btn btn-block btn-primary" style="padding: 10px; font-size: 24px;" on:click={save}>Save and Get Started!</button>
    </div>
  </div>
</Screen>